# Optimisation et présentation des résultats

Nous allons commencer a travailler avec des données numériques en utilisant la librarie **numpy**, à résoudre des problèmes simples d'optimisation numériques en utilisant la librarie **scipy** et en particulier les fonctions de **scipy.optimize**, et enfin nous présenterons les résutats sous forme "textuelle" avec la fonction **print**, et de graphiques avec **matplotlib**.

## Références:

- print: [exemples](https://www.python-course.eu/python3_formatted_output.php) (détaillés)
- numpy: [tutoriel détaillé](https://www.python-course.eu/numpy.php)
- matplotlib: [exemples](https://matplotlib.org/stable/tutorials/introductory/sample_plots.html), [documentation](https://matplotlib.org/stable/users/index.html), [styles](https://matplotlib.org/3.1.0/gallery/style_sheets/style_sheets_reference.html)
- scipy-optimize: [documentation](https://docs.scipy.org/doc/scipy/reference/optimize.html)
$\def\R{\mathbb{R}}$

# 1. Le problème de choix du consommateur

Nous allons considérer un consommateur dont les préférences en matière de consommation sont représentées par une fonction d'utilité,
$
\begin{align*}
u(q_1, q_2): \R_{+}^2 &\rightarrow \R.
\end{align*}
$

On considère ainsi le cadre de paniers de biens à deux composantes. D'autre part, nous supposons que le consommateur dispose d'un revenu $R$ déterminé de façon exogène par rapport à son choix de consommation. Enfin le vecteur de prix $p = (p_1, p_2)$ est aussi exogène, le consommateur le considérant comme donné.

Le problème de choix du consommateur consiste à déterminer le panier *optimal* $q^* = (q_1^*, q_2^*)$ au sens où il maximise son utilité sous sa contrainte de budjet. Formellement,

$
\begin{align*}
V(p_1,p_2, R) &= \max_{q_1, q_2} u(q_1, q_2)\\
&s.c.,\\
p_1q_1 + p_2q_2\leq R,& \quad p_1, p_2, R > 0,\\
% &q_1, q_2 \geq 0
\end{align*}
$

## Exemple: fonction d'utilité Cobb-Douglas.

Dans cet exemple $u(\cdot)$ est donnée par,

$
\begin{align*}
u(q_1, q_2) &= q_1^\alpha q_2^{1-\alpha}, \quad \alpha \in (0, 1).
\end{align*}
$

Les solutions optimales sont ici:

$
\begin{align*}
q^{*}_1 &= \alpha\frac{R}{p_1},\\
q^{*}_2 &= (1-\alpha)\frac{R}{p_2}.
\end{align*}
$

$q^*_1$, et $q^*_2$ sont des fonctions des prix des biens, et du revenu, qu'on appelle *fonctions de demande*, et que l'on note respectivement $q_1^d(p, R)$, et $q_2^d(p, R)$.

# 2. Calcul numérique avec numpy

In [1]:
import numpy as np # importation de la bibliothèque numpy.

## L'**Array** numpy

Un array de numpy est semblable à une liste avec cependant les deux différences suivantes:

1. Les éléments sont homogènes.
2. Une opération de *slicing* sur un array produit une "vue"(à *view*) de celui-ci plutôt que d'extraire du contenu.

## Les bases

Un array numpy peut être crée à partir d'une liste et être multidimensionel.

In [10]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # une dimension
B = np.array([[3.4, 8.7, 9.9], 
              [1.1, -7.8, -0.7],
              [4.1, 12.3, 4.8]]) # deux dimensions

print(type(A),type(B)) # type
print(A.dtype,B.dtype) # le type des éléments dans les array
print(A.ndim,B.ndim) # dimensions
print(A.shape,B.shape) # "shape" (1d: nombre d'éléments, 2d: nombre de lignes x nombre de colonnes)
print(A.size,B.size) # taille(i.e., nombre d'élèments)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
int64 float64
1 2
(10,) (3, 3)
10 9


Le **Slicing** sur un array produit une vue de celui-ci:




In [11]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
B = A.copy() # B est une copie de A
C = A[2:6] # C obtenu par slicing sur A produit une vue de A
C[0] = 0
C[1] = 0
print(A) # A est modifié
print(B) # B ne l'est pas

[0 1 0 0 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Les array numpy peuvent être créés aussi en appliquant des fonction numpy

In [8]:
print(np.ones((2,3))) # array rempli de 1
print(np.zeros((4,2))) # array rempli de zéros
print(np.full((3, 5), 3.14)) # array rempli d'un nombre désiré
print(np.linspace(0,1,6)) # suite: interpolation linéaire entre deux bornes
print(np.arange(0, 10)) # suite de nombres équidistants.
print(np.eye(3)) # array sous forme d'une matrice identité

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[0.  0.2 0.4 0.6 0.8 1. ]
[0 1 2 3 4 5 6 7 8 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Remarque**: dans les fonctions précédentes on peut ajouter un argument dtype pour contraindre le type du array(int, ou float).

In [10]:
print(np.ones((2,3), dtype=int)) # array rempli de 1
print(np.zeros((4,2), dtype=int)) # array rempli de zéros

[[1 1 1]
 [1 1 1]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]]


## Opérations mathématiques sur les array

In [2]:
A = np.array([[1,0],[0,1]])
B = np.array([[2,2],[2,2]])

print(A,'\n')
print(B, '\n')
print(A + B,'\n')
print(A - B,'\n')
print(A * B,'\n') # produit élément par élément
print(A / B,'\n') # division élément par élément
print(A @ B,'\n') # produit matriciel

[[1 0]
 [0 1]] 

[[2 2]
 [2 2]] 

[[3 2]
 [2 3]] 

[[-1 -2]
 [-2 -1]] 

[[2 0]
 [0 2]] 

[[0.5 0. ]
 [0.  0.5]] 

[[2 2]
 [2 2]] 



## Broadcasting

Le broadcasting est un ensemble de régles qui décrivent comment des opérations binaires s'appliquent sur des array de format(shape) différents. Nous allons en donner une présentation assez brève et ce faisant moins détaillée que celles que vous trouverez [ici](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html), et [ici](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html) notamment, et que nous reprenons partiellement dans ce qui suit.

Pour commencer rappelons que sur des arrays de même format(soit avec le même nombre de dimensions, et même longueur pour chaque dimension) les opération binaires s'executent élément par élément. 

Illustrons cela par l'exemple suivant:


In [7]:
A = np.array([0, 1, 2])
B = np.array([5, 5, 5])
print(A, A.shape, '\n')
print(B, B.shape, '\n')
print(A + B, (A + B).shape, '\n')

[0 1 2] (3,) 

[5 5 5] (3,) 

[5 6 7] (3,) 



A présent considérons la somme de l'array $A$ précédent et d'un scalaire, par exemple $5$, lequel peut être vu comme un array de dimension nulle:

In [8]:
print(A + 5, (A + 5).shape, '\n')

[5 6 7] (3,) 



Cette opération donne le même résultat que celle précédente additionnant $A$ et $B$. Ceci laisse à penser qu'en executant $A + 5$ la valeur $5$ a été dupliquée pour produire l'array $[5, 5, 5]$ afin d'additionner des array de même format. Cependant cette opération de duplication n'est pas effectivement réalisée par numpy et est seulement employée ici pour une compréhension du broadcasting. Elle concerne aussi des arrays avec plus de dimensions que $A$. Par exemple:

In [9]:
M = np.ones((3, 3))
print(M, M.shape, '\n')
print(M + A, (M + A).shape, '\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3) 

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] (3, 3) 



En poursuivant l'explication du cas avec un scalaire, dans cet exemple l'array $A$ qui a une seule dimension est dupliqué de manière à avoir le même nombre de dimensions que $M$, soit 2, et le même nombre d'éléments. Ceci correspond à l'array:

In [20]:
A = np.full((3, 3), A)
print(A , '\n')
print((M + A) , (M + A).shape, '\n')

[[0 1 2]
 [0 1 2]
 [0 1 2]] 

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] (3, 3) 



Dans les exemples précédents, le broadcasting(la duplication) ne s'est appliqué que sur l'un des arrays impliqué dans l'opération considérée(l'addition), soit sur $5$ et $A$. Mais il peut aussi s'appliquer sur deux arrays, par exemple: 

In [3]:
A = np.arange(3)
B = np.arange(3)[:, np.newaxis]

print(A, A.shape, "\n")
print(B, B.shape, "\n")
print(A + B, (A + B).shape, "\n")

[0 1 2] (3,) 

[[0]
 [1]
 [2]] (3, 1) 

[[0 1 2]
 [1 2 3]
 [2 3 4]] (3, 3) 



Ici les deux arrays ont été dupliqués pour qu'ils aient un même format. Ainsi dans le cas de $A$ cela correspond à:

In [4]:
A = np.full((3, 3), A)
print(A, A.shape, "\n")

[[0 1 2]
 [0 1 2]
 [0 1 2]] (3, 3) 



et pour $B$:

In [5]:
B = np.full((3, 3), B)
print(B, B.shape, "\n")

[[0 0 0]
 [1 1 1]
 [2 2 2]] (3, 3) 



On vérifier qu'on obtient le même résultat:

In [6]:
print(A + B, (A + B).shape, "\n")

[[0 1 2]
 [1 2 3]
 [2 3 4]] (3, 3) 



**Régles générales du broadcasting:** 
-

In [ ]:
A = np.full((3, 3), B)
print(A, A.shape, "\n")

In [13]:
A = np.array([ [10, 20, 30], [40, 50, 60] ]) # shape = (2,3) 
B = np.array([1, 2, 3]) # shape = (3,) = (1,3)
C = np.array([[1],[2]]) # shape = (2,1)


print(A, A.shape, '\n')
print(B, B.shape, '\n') 
print(C, C.shape, '\n') 

print(A*B,'\n') # chaque colonne est multiplié par B
print(A*C,'\n') # chaque colonne est multiplié par C

[[10 20 30]
 [40 50 60]] (2, 3) 

[1 2 3] (3,) 

[[1]
 [2]] (2, 1) 

[[ 10  40  90]
 [ 40 100 180]] 

[[ 10  20  30]
 [ 80 100 120]] 



**General rule du broadcasting**: Numpy arrays can be added/substracted/multiplied/divided if they in all dimensions have the same size or one of them has a size of one. If the numpy arrays differ in number of dimensions, this only has to be true for the (inner) dimensions they share.

Dans le cas où le broadcasting est impossible on peut employer np.newaxis:

In [14]:
A = np.array([1, 2, 3]) # array 1D, shape = (3,)
B = np.array([1,2]) # array 1D, shape = (2,)

# On ne peut pas broadcaster B sur A, car aucun des deux n'a deux dimensions.
# On utilise alors newaxis
print(A[:,np.newaxis], A[:,np.newaxis].shape, '\n') # Is now (3,1)
print(B[np.newaxis,:], B[np.newaxis,:].shape, '\n') # Is now (1,2)

print(A[:,np.newaxis]*B[np.newaxis,:], '\n') # A is column vector, B is row vector
print(A[np.newaxis,:]*B[:,np.newaxis]) # A is row vector, B is column vector


[[1]
 [2]
 [3]] (3, 1) 

[[1 2]] (1, 2) 

[[1 2]
 [2 4]
 [3 6]] 

[[1 2 3]
 [2 4 6]]
